// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dailyverse/v1/daily-verse.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.biblecontentmedia.dailyverse.protos;

@kotlin.jvm.JvmName("-initializedailyVerseResponse")
public inline fun dailyVerseResponse(block: com.biblecontentmedia.dailyverse.protos.DailyVerseResponseKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.DailyVerseResponse =
  com.biblecontentmedia.dailyverse.protos.DailyVerseResponseKt.Dsl._create(com.biblecontentmedia.dailyverse.protos.DailyVerseResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.biblecontentmedia.dailyverse.protos.v1.DailyVerseResponse`
 */
public object DailyVerseResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.biblecontentmedia.dailyverse.protos.DailyVerseResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.biblecontentmedia.dailyverse.protos.DailyVerseResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.biblecontentmedia.dailyverse.protos.DailyVerseResponse = _builder.build()

    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.VerseSummary verse = 1;`
     */
    public var verse: com.biblecontentmedia.dailyverse.protos.VerseSummary
      @JvmName("getVerse")
      get() = _builder.getVerse()
      @JvmName("setVerse")
      set(value) {
        _builder.setVerse(value)
      }
    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.VerseSummary verse = 1;`
     */
    public fun clearVerse() {
      _builder.clearVerse()
    }
    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.VerseSummary verse = 1;`
     * @return Whether the verse field is set.
     */
    public fun hasVerse(): kotlin.Boolean {
      return _builder.hasVerse()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.biblecontentmedia.dailyverse.protos.DailyVerseResponse.copy(block: `com.biblecontentmedia.dailyverse.protos`.DailyVerseResponseKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.DailyVerseResponse =
  `com.biblecontentmedia.dailyverse.protos`.DailyVerseResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.biblecontentmedia.dailyverse.protos.DailyVerseResponseOrBuilder.verseOrNull: com.biblecontentmedia.dailyverse.protos.VerseSummary?
  get() = if (hasVerse()) getVerse() else null

