// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dailyverse/v1/daily-verse.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.biblecontentmedia.dailyverse.protos;

@kotlin.jvm.JvmName("-initializegetDailyVerseRequest")
public inline fun getDailyVerseRequest(block: com.biblecontentmedia.dailyverse.protos.GetDailyVerseRequestKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.GetDailyVerseRequest =
  com.biblecontentmedia.dailyverse.protos.GetDailyVerseRequestKt.Dsl._create(com.biblecontentmedia.dailyverse.protos.GetDailyVerseRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.biblecontentmedia.dailyverse.protos.v1.GetDailyVerseRequest`
 */
public object GetDailyVerseRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.biblecontentmedia.dailyverse.protos.GetDailyVerseRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.biblecontentmedia.dailyverse.protos.GetDailyVerseRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.biblecontentmedia.dailyverse.protos.GetDailyVerseRequest = _builder.build()

    /**
     * `string language = 1;`
     */
    public var language: kotlin.String
      @JvmName("getLanguage")
      get() = _builder.getLanguage()
      @JvmName("setLanguage")
      set(value) {
        _builder.setLanguage(value)
      }
    /**
     * `string language = 1;`
     */
    public fun clearLanguage() {
      _builder.clearLanguage()
    }

    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.BibleVersion version = 2;`
     */
    public var version: com.biblecontentmedia.dailyverse.api.proto.BibleVersion
      @JvmName("getVersion")
      get() = _builder.getVersion()
      @JvmName("setVersion")
      set(value) {
        _builder.setVersion(value)
      }
    public var versionValue: kotlin.Int
      @JvmName("getVersionValue")
      get() = _builder.getVersionValue()
      @JvmName("setVersionValue")
      set(value) {
        _builder.setVersionValue(value)
      }
    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.BibleVersion version = 2;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.biblecontentmedia.dailyverse.protos.GetDailyVerseRequest.copy(block: `com.biblecontentmedia.dailyverse.protos`.GetDailyVerseRequestKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.GetDailyVerseRequest =
  `com.biblecontentmedia.dailyverse.protos`.GetDailyVerseRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

