// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dailyverse/v1/daily-verse.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.biblecontentmedia.dailyverse.protos;

@kotlin.jvm.JvmName("-initializegetVerseRequest")
public inline fun getVerseRequest(block: com.biblecontentmedia.dailyverse.protos.GetVerseRequestKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.GetVerseRequest =
  com.biblecontentmedia.dailyverse.protos.GetVerseRequestKt.Dsl._create(com.biblecontentmedia.dailyverse.protos.GetVerseRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.biblecontentmedia.dailyverse.protos.v1.GetVerseRequest`
 */
public object GetVerseRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.biblecontentmedia.dailyverse.protos.GetVerseRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.biblecontentmedia.dailyverse.protos.GetVerseRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.biblecontentmedia.dailyverse.protos.GetVerseRequest = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.biblecontentmedia.dailyverse.protos.GetVerseRequest.copy(block: `com.biblecontentmedia.dailyverse.protos`.GetVerseRequestKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.GetVerseRequest =
  `com.biblecontentmedia.dailyverse.protos`.GetVerseRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

