// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dailyverse/v1/daily-verse.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.biblecontentmedia.dailyverse.protos;

@kotlin.jvm.JvmName("-initializelistVersesResponse")
public inline fun listVersesResponse(block: com.biblecontentmedia.dailyverse.protos.ListVersesResponseKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.ListVersesResponse =
  com.biblecontentmedia.dailyverse.protos.ListVersesResponseKt.Dsl._create(com.biblecontentmedia.dailyverse.protos.ListVersesResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.biblecontentmedia.dailyverse.protos.v1.ListVersesResponse`
 */
public object ListVersesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.biblecontentmedia.dailyverse.protos.ListVersesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.biblecontentmedia.dailyverse.protos.ListVersesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.biblecontentmedia.dailyverse.protos.ListVersesResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class VersesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .com.biblecontentmedia.dailyverse.protos.v1.VerseSummary verses = 1;`
     */
     public val verses: com.google.protobuf.kotlin.DslList<com.biblecontentmedia.dailyverse.protos.VerseSummary, VersesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getVersesList()
      )
    /**
     * `repeated .com.biblecontentmedia.dailyverse.protos.v1.VerseSummary verses = 1;`
     * @param value The verses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addVerses")
    public fun com.google.protobuf.kotlin.DslList<com.biblecontentmedia.dailyverse.protos.VerseSummary, VersesProxy>.add(value: com.biblecontentmedia.dailyverse.protos.VerseSummary) {
      _builder.addVerses(value)
    }
    /**
     * `repeated .com.biblecontentmedia.dailyverse.protos.v1.VerseSummary verses = 1;`
     * @param value The verses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignVerses")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.biblecontentmedia.dailyverse.protos.VerseSummary, VersesProxy>.plusAssign(value: com.biblecontentmedia.dailyverse.protos.VerseSummary) {
      add(value)
    }
    /**
     * `repeated .com.biblecontentmedia.dailyverse.protos.v1.VerseSummary verses = 1;`
     * @param values The verses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllVerses")
    public fun com.google.protobuf.kotlin.DslList<com.biblecontentmedia.dailyverse.protos.VerseSummary, VersesProxy>.addAll(values: kotlin.collections.Iterable<com.biblecontentmedia.dailyverse.protos.VerseSummary>) {
      _builder.addAllVerses(values)
    }
    /**
     * `repeated .com.biblecontentmedia.dailyverse.protos.v1.VerseSummary verses = 1;`
     * @param values The verses to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllVerses")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.biblecontentmedia.dailyverse.protos.VerseSummary, VersesProxy>.plusAssign(values: kotlin.collections.Iterable<com.biblecontentmedia.dailyverse.protos.VerseSummary>) {
      addAll(values)
    }
    /**
     * `repeated .com.biblecontentmedia.dailyverse.protos.v1.VerseSummary verses = 1;`
     * @param index The index to set the value at.
     * @param value The verses to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setVerses")
    public operator fun com.google.protobuf.kotlin.DslList<com.biblecontentmedia.dailyverse.protos.VerseSummary, VersesProxy>.set(index: kotlin.Int, value: com.biblecontentmedia.dailyverse.protos.VerseSummary) {
      _builder.setVerses(index, value)
    }
    /**
     * `repeated .com.biblecontentmedia.dailyverse.protos.v1.VerseSummary verses = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearVerses")
    public fun com.google.protobuf.kotlin.DslList<com.biblecontentmedia.dailyverse.protos.VerseSummary, VersesProxy>.clear() {
      _builder.clearVerses()
    }


    /**
     * `string next_page_token = 2;`
     */
    public var nextPageToken: kotlin.String
      @JvmName("getNextPageToken")
      get() = _builder.getNextPageToken()
      @JvmName("setNextPageToken")
      set(value) {
        _builder.setNextPageToken(value)
      }
    /**
     * `string next_page_token = 2;`
     */
    public fun clearNextPageToken() {
      _builder.clearNextPageToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.biblecontentmedia.dailyverse.protos.ListVersesResponse.copy(block: `com.biblecontentmedia.dailyverse.protos`.ListVersesResponseKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.ListVersesResponse =
  `com.biblecontentmedia.dailyverse.protos`.ListVersesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

