// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dailyverse/v1/daily-verse.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.biblecontentmedia.dailyverse.protos;

@kotlin.jvm.JvmName("-initializelistVersesRequest")
public inline fun listVersesRequest(block: com.biblecontentmedia.dailyverse.protos.ListVersesRequestKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.ListVersesRequest =
  com.biblecontentmedia.dailyverse.protos.ListVersesRequestKt.Dsl._create(com.biblecontentmedia.dailyverse.protos.ListVersesRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.biblecontentmedia.dailyverse.protos.v1.ListVersesRequest`
 */
public object ListVersesRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.biblecontentmedia.dailyverse.protos.ListVersesRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.biblecontentmedia.dailyverse.protos.ListVersesRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.biblecontentmedia.dailyverse.protos.ListVersesRequest = _builder.build()

    /**
     * `int32 page_size = 1;`
     */
    public var pageSize: kotlin.Int
      @JvmName("getPageSize")
      get() = _builder.getPageSize()
      @JvmName("setPageSize")
      set(value) {
        _builder.setPageSize(value)
      }
    /**
     * `int32 page_size = 1;`
     */
    public fun clearPageSize() {
      _builder.clearPageSize()
    }

    /**
     * `string page_token = 2;`
     */
    public var pageToken: kotlin.String
      @JvmName("getPageToken")
      get() = _builder.getPageToken()
      @JvmName("setPageToken")
      set(value) {
        _builder.setPageToken(value)
      }
    /**
     * `string page_token = 2;`
     */
    public fun clearPageToken() {
      _builder.clearPageToken()
    }

    /**
     * `string language = 3;`
     */
    public var language: kotlin.String
      @JvmName("getLanguage")
      get() = _builder.getLanguage()
      @JvmName("setLanguage")
      set(value) {
        _builder.setLanguage(value)
      }
    /**
     * `string language = 3;`
     */
    public fun clearLanguage() {
      _builder.clearLanguage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.biblecontentmedia.dailyverse.protos.ListVersesRequest.copy(block: `com.biblecontentmedia.dailyverse.protos`.ListVersesRequestKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.ListVersesRequest =
  `com.biblecontentmedia.dailyverse.protos`.ListVersesRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

