// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dailyverse/v1/daily-verse.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.biblecontentmedia.dailyverse.protos;

@kotlin.jvm.JvmName("-initializeverse")
public inline fun verse(block: com.biblecontentmedia.dailyverse.protos.VerseKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.Verse =
  com.biblecontentmedia.dailyverse.protos.VerseKt.Dsl._create(com.biblecontentmedia.dailyverse.protos.Verse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.biblecontentmedia.dailyverse.protos.v1.Verse`
 */
public object VerseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.biblecontentmedia.dailyverse.protos.Verse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.biblecontentmedia.dailyverse.protos.Verse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.biblecontentmedia.dailyverse.protos.Verse = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.VerseSummary summary = 2;`
     */
    public var summary: com.biblecontentmedia.dailyverse.protos.VerseSummary
      @JvmName("getSummary")
      get() = _builder.getSummary()
      @JvmName("setSummary")
      set(value) {
        _builder.setSummary(value)
      }
    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.VerseSummary summary = 2;`
     */
    public fun clearSummary() {
      _builder.clearSummary()
    }
    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.VerseSummary summary = 2;`
     * @return Whether the summary field is set.
     */
    public fun hasSummary(): kotlin.Boolean {
      return _builder.hasSummary()
    }

    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.VerseMetadata metadata = 3;`
     */
    public var metadata: com.biblecontentmedia.dailyverse.protos.VerseMetadata
      @JvmName("getMetadata")
      get() = _builder.getMetadata()
      @JvmName("setMetadata")
      set(value) {
        _builder.setMetadata(value)
      }
    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.VerseMetadata metadata = 3;`
     */
    public fun clearMetadata() {
      _builder.clearMetadata()
    }
    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.VerseMetadata metadata = 3;`
     * @return Whether the metadata field is set.
     */
    public fun hasMetadata(): kotlin.Boolean {
      return _builder.hasMetadata()
    }

    /**
     * `.google.protobuf.Timestamp created_at = 4;`
     */
    public var createdAt: com.google.protobuf.Timestamp
      @JvmName("getCreatedAt")
      get() = _builder.getCreatedAt()
      @JvmName("setCreatedAt")
      set(value) {
        _builder.setCreatedAt(value)
      }
    /**
     * `.google.protobuf.Timestamp created_at = 4;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
    /**
     * `.google.protobuf.Timestamp created_at = 4;`
     * @return Whether the createdAt field is set.
     */
    public fun hasCreatedAt(): kotlin.Boolean {
      return _builder.hasCreatedAt()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class TagsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string tags = 5;`
     * @return A list containing the tags.
     */
    public val tags: com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getTagsList()
      )
    /**
     * `repeated string tags = 5;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.add(value: kotlin.String) {
      _builder.addTags(value)
    }
    /**
     * `repeated string tags = 5;`
     * @param value The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string tags = 5;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllTags(values)
    }
    /**
     * `repeated string tags = 5;`
     * @param values The tags to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllTags")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string tags = 5;`
     * @param index The index to set the value at.
     * @param value The tags to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setTags")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setTags(index, value)
    }/**
     * `repeated string tags = 5;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearTags")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, TagsProxy>.clear() {
      _builder.clearTags()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.biblecontentmedia.dailyverse.protos.Verse.copy(block: `com.biblecontentmedia.dailyverse.protos`.VerseKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.Verse =
  `com.biblecontentmedia.dailyverse.protos`.VerseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.biblecontentmedia.dailyverse.protos.VerseOrBuilder.summaryOrNull: com.biblecontentmedia.dailyverse.protos.VerseSummary?
  get() = if (hasSummary()) getSummary() else null

public val com.biblecontentmedia.dailyverse.protos.VerseOrBuilder.metadataOrNull: com.biblecontentmedia.dailyverse.protos.VerseMetadata?
  get() = if (hasMetadata()) getMetadata() else null

public val com.biblecontentmedia.dailyverse.protos.VerseOrBuilder.createdAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasCreatedAt()) getCreatedAt() else null

