// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dailyverse/v1/daily-verse.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.biblecontentmedia.dailyverse.protos;

@kotlin.jvm.JvmName("-initializeverseMetadata")
public inline fun verseMetadata(block: com.biblecontentmedia.dailyverse.protos.VerseMetadataKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.VerseMetadata =
  com.biblecontentmedia.dailyverse.protos.VerseMetadataKt.Dsl._create(com.biblecontentmedia.dailyverse.protos.VerseMetadata.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.biblecontentmedia.dailyverse.protos.v1.VerseMetadata`
 */
public object VerseMetadataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.biblecontentmedia.dailyverse.protos.VerseMetadata.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.biblecontentmedia.dailyverse.protos.VerseMetadata.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.biblecontentmedia.dailyverse.protos.VerseMetadata = _builder.build()

    /**
     * `string text = 1;`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * `string reference = 2;`
     */
    public var reference: kotlin.String
      @JvmName("getReference")
      get() = _builder.getReference()
      @JvmName("setReference")
      set(value) {
        _builder.setReference(value)
      }
    /**
     * `string reference = 2;`
     */
    public fun clearReference() {
      _builder.clearReference()
    }

    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.BibleVersion version = 3;`
     */
    public var version: com.biblecontentmedia.dailyverse.api.proto.BibleVersion
      @JvmName("getVersion")
      get() = _builder.getVersion()
      @JvmName("setVersion")
      set(value) {
        _builder.setVersion(value)
      }
    public var versionValue: kotlin.Int
      @JvmName("getVersionValue")
      get() = _builder.getVersionValue()
      @JvmName("setVersionValue")
      set(value) {
        _builder.setVersionValue(value)
      }
    /**
     * `.com.biblecontentmedia.dailyverse.protos.v1.BibleVersion version = 3;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * `string language = 4;`
     */
    public var language: kotlin.String
      @JvmName("getLanguage")
      get() = _builder.getLanguage()
      @JvmName("setLanguage")
      set(value) {
        _builder.setLanguage(value)
      }
    /**
     * `string language = 4;`
     */
    public fun clearLanguage() {
      _builder.clearLanguage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.biblecontentmedia.dailyverse.protos.VerseMetadata.copy(block: `com.biblecontentmedia.dailyverse.protos`.VerseMetadataKt.Dsl.() -> kotlin.Unit): com.biblecontentmedia.dailyverse.protos.VerseMetadata =
  `com.biblecontentmedia.dailyverse.protos`.VerseMetadataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

