// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bible/version/v1/bible-version.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.biblecontentmedia.dailyverse.api.proto;

