// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/v1/auth.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.apptorise.dailyverse.protos.auth;

@kotlin.jvm.JvmName("-initializeauthResponse")
public inline fun authResponse(block: com.apptorise.dailyverse.protos.auth.AuthResponseKt.Dsl.() -> kotlin.Unit): com.apptorise.dailyverse.protos.auth.AuthResponse =
  com.apptorise.dailyverse.protos.auth.AuthResponseKt.Dsl._create(com.apptorise.dailyverse.protos.auth.AuthResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.apptorise.dailyverse.protos.auth.v1.AuthResponse`
 */
public object AuthResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.apptorise.dailyverse.protos.auth.AuthResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.apptorise.dailyverse.protos.auth.AuthResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.apptorise.dailyverse.protos.auth.AuthResponse = _builder.build()

    /**
     * `string access_token = 1;`
     */
    public var accessToken: kotlin.String
      @JvmName("getAccessToken")
      get() = _builder.getAccessToken()
      @JvmName("setAccessToken")
      set(value) {
        _builder.setAccessToken(value)
      }
    /**
     * `string access_token = 1;`
     */
    public fun clearAccessToken() {
      _builder.clearAccessToken()
    }

    /**
     * `string refresh_token = 2;`
     */
    public var refreshToken: kotlin.String
      @JvmName("getRefreshToken")
      get() = _builder.getRefreshToken()
      @JvmName("setRefreshToken")
      set(value) {
        _builder.setRefreshToken(value)
      }
    /**
     * `string refresh_token = 2;`
     */
    public fun clearRefreshToken() {
      _builder.clearRefreshToken()
    }

    /**
     * `.com.apptorise.dailyverse.protos.auth.v1.User user = 3;`
     */
    public var user: com.apptorise.dailyverse.protos.auth.User
      @JvmName("getUser")
      get() = _builder.getUser()
      @JvmName("setUser")
      set(value) {
        _builder.setUser(value)
      }
    /**
     * `.com.apptorise.dailyverse.protos.auth.v1.User user = 3;`
     */
    public fun clearUser() {
      _builder.clearUser()
    }
    /**
     * `.com.apptorise.dailyverse.protos.auth.v1.User user = 3;`
     * @return Whether the user field is set.
     */
    public fun hasUser(): kotlin.Boolean {
      return _builder.hasUser()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.apptorise.dailyverse.protos.auth.AuthResponse.copy(block: `com.apptorise.dailyverse.protos.auth`.AuthResponseKt.Dsl.() -> kotlin.Unit): com.apptorise.dailyverse.protos.auth.AuthResponse =
  `com.apptorise.dailyverse.protos.auth`.AuthResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.apptorise.dailyverse.protos.auth.AuthResponseOrBuilder.userOrNull: com.apptorise.dailyverse.protos.auth.User?
  get() = if (hasUser()) getUser() else null

