// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/v1/auth.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.apptorise.dailyverse.protos.auth;

