// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/v1/auth.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.apptorise.dailyverse.protos.auth;

@kotlin.jvm.JvmName("-initializeemailSignInRequest")
public inline fun emailSignInRequest(block: com.apptorise.dailyverse.protos.auth.EmailSignInRequestKt.Dsl.() -> kotlin.Unit): com.apptorise.dailyverse.protos.auth.EmailSignInRequest =
  com.apptorise.dailyverse.protos.auth.EmailSignInRequestKt.Dsl._create(com.apptorise.dailyverse.protos.auth.EmailSignInRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.apptorise.dailyverse.protos.auth.v1.EmailSignInRequest`
 */
public object EmailSignInRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.apptorise.dailyverse.protos.auth.EmailSignInRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.apptorise.dailyverse.protos.auth.EmailSignInRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.apptorise.dailyverse.protos.auth.EmailSignInRequest = _builder.build()

    /**
     * `string email = 1;`
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * `string email = 1;`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * `string password = 2;`
     */
    public var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.getPassword()
      @JvmName("setPassword")
      set(value) {
        _builder.setPassword(value)
      }
    /**
     * `string password = 2;`
     */
    public fun clearPassword() {
      _builder.clearPassword()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.apptorise.dailyverse.protos.auth.EmailSignInRequest.copy(block: `com.apptorise.dailyverse.protos.auth`.EmailSignInRequestKt.Dsl.() -> kotlin.Unit): com.apptorise.dailyverse.protos.auth.EmailSignInRequest =
  `com.apptorise.dailyverse.protos.auth`.EmailSignInRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

