// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/v1/auth.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.apptorise.dailyverse.protos.auth;

@kotlin.jvm.JvmName("-initializegoogleSignInRequest")
public inline fun googleSignInRequest(block: com.apptorise.dailyverse.protos.auth.GoogleSignInRequestKt.Dsl.() -> kotlin.Unit): com.apptorise.dailyverse.protos.auth.GoogleSignInRequest =
  com.apptorise.dailyverse.protos.auth.GoogleSignInRequestKt.Dsl._create(com.apptorise.dailyverse.protos.auth.GoogleSignInRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.apptorise.dailyverse.protos.auth.v1.GoogleSignInRequest`
 */
public object GoogleSignInRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.apptorise.dailyverse.protos.auth.GoogleSignInRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.apptorise.dailyverse.protos.auth.GoogleSignInRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.apptorise.dailyverse.protos.auth.GoogleSignInRequest = _builder.build()

    /**
     * `string id_token = 1;`
     */
    public var idToken: kotlin.String
      @JvmName("getIdToken")
      get() = _builder.getIdToken()
      @JvmName("setIdToken")
      set(value) {
        _builder.setIdToken(value)
      }
    /**
     * `string id_token = 1;`
     */
    public fun clearIdToken() {
      _builder.clearIdToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.apptorise.dailyverse.protos.auth.GoogleSignInRequest.copy(block: `com.apptorise.dailyverse.protos.auth`.GoogleSignInRequestKt.Dsl.() -> kotlin.Unit): com.apptorise.dailyverse.protos.auth.GoogleSignInRequest =
  `com.apptorise.dailyverse.protos.auth`.GoogleSignInRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

