// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/v1/auth.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.apptorise.dailyverse.protos.auth;

@kotlin.jvm.JvmName("-initializerefreshRequest")
public inline fun refreshRequest(block: com.apptorise.dailyverse.protos.auth.RefreshRequestKt.Dsl.() -> kotlin.Unit): com.apptorise.dailyverse.protos.auth.RefreshRequest =
  com.apptorise.dailyverse.protos.auth.RefreshRequestKt.Dsl._create(com.apptorise.dailyverse.protos.auth.RefreshRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.apptorise.dailyverse.protos.auth.v1.RefreshRequest`
 */
public object RefreshRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.apptorise.dailyverse.protos.auth.RefreshRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.apptorise.dailyverse.protos.auth.RefreshRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.apptorise.dailyverse.protos.auth.RefreshRequest = _builder.build()

    /**
     * `string refresh_token = 1;`
     */
    public var refreshToken: kotlin.String
      @JvmName("getRefreshToken")
      get() = _builder.getRefreshToken()
      @JvmName("setRefreshToken")
      set(value) {
        _builder.setRefreshToken(value)
      }
    /**
     * `string refresh_token = 1;`
     */
    public fun clearRefreshToken() {
      _builder.clearRefreshToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.apptorise.dailyverse.protos.auth.RefreshRequest.copy(block: `com.apptorise.dailyverse.protos.auth`.RefreshRequestKt.Dsl.() -> kotlin.Unit): com.apptorise.dailyverse.protos.auth.RefreshRequest =
  `com.apptorise.dailyverse.protos.auth`.RefreshRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

