// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: user/v1/user.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.apptorise.dailyverse.protos.auth;

@kotlin.jvm.JvmName("-initializeuser")
public inline fun user(block: com.apptorise.dailyverse.protos.auth.UserKt.Dsl.() -> kotlin.Unit): com.apptorise.dailyverse.protos.auth.User =
  com.apptorise.dailyverse.protos.auth.UserKt.Dsl._create(com.apptorise.dailyverse.protos.auth.User.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.apptorise.dailyverse.protos.auth.v1.User`
 */
public object UserKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.apptorise.dailyverse.protos.auth.User.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.apptorise.dailyverse.protos.auth.User.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.apptorise.dailyverse.protos.auth.User = _builder.build()

    /**
     * `string id = 1;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string email = 2;`
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * `string email = 2;`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * `string first_name = 3;`
     */
    public var firstName: kotlin.String
      @JvmName("getFirstName")
      get() = _builder.getFirstName()
      @JvmName("setFirstName")
      set(value) {
        _builder.setFirstName(value)
      }
    /**
     * `string first_name = 3;`
     */
    public fun clearFirstName() {
      _builder.clearFirstName()
    }

    /**
     * `string last_name = 4;`
     */
    public var lastName: kotlin.String
      @JvmName("getLastName")
      get() = _builder.getLastName()
      @JvmName("setLastName")
      set(value) {
        _builder.setLastName(value)
      }
    /**
     * `string last_name = 4;`
     */
    public fun clearLastName() {
      _builder.clearLastName()
    }

    /**
     * `string photo_url = 5;`
     */
    public var photoUrl: kotlin.String
      @JvmName("getPhotoUrl")
      get() = _builder.getPhotoUrl()
      @JvmName("setPhotoUrl")
      set(value) {
        _builder.setPhotoUrl(value)
      }
    /**
     * `string photo_url = 5;`
     */
    public fun clearPhotoUrl() {
      _builder.clearPhotoUrl()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.apptorise.dailyverse.protos.auth.User.copy(block: `com.apptorise.dailyverse.protos.auth`.UserKt.Dsl.() -> kotlin.Unit): com.apptorise.dailyverse.protos.auth.User =
  `com.apptorise.dailyverse.protos.auth`.UserKt.Dsl._create(this.toBuilder()).apply { block() }._build()

