// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: user/v1/user.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.apptorise.dailyverse.protos.auth;

